--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 25.10.2023 18:01:00
-- Server version: 8.0.11
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE chess_db;

--
-- Drop table `chess notation_ht`
--
DROP TABLE IF EXISTS `chess notation_ht`;

--
-- Drop table `chess_notation_db`
--
DROP TABLE IF EXISTS chess_notation_db;

--
-- Drop table `chess_players`
--
DROP TABLE IF EXISTS chess_players;

--
-- Drop table `colors`
--
DROP TABLE IF EXISTS colors;

--
-- Drop table `figures`
--
DROP TABLE IF EXISTS figures;

--
-- Drop table `main_chessboard`
--
DROP TABLE IF EXISTS main_chessboard;

--
-- Drop table `move_options`
--
DROP TABLE IF EXISTS move_options;

--
-- Set default database
--
USE chess_db;

--
-- Create table `move_options`
--
CREATE TABLE move_options (
  id int(11) DEFAULT NULL,
  figure_id varchar(255) DEFAULT NULL,
  different_x varchar(255) DEFAULT NULL,
  different_y varchar(255) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `main_chessboard`
--
CREATE TABLE main_chessboard (
  id int(11) DEFAULT NULL,
  x_position tinyint(4) DEFAULT NULL COMMENT '1-8',
  y_position tinyint(4) DEFAULT NULL COMMENT 'A-H',
  color char(20) DEFAULT NULL COMMENT 'black or white'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `figures`
--
CREATE TABLE figures (
  id int(11) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  code varchar(255) DEFAULT NULL,
  color_id int(11) DEFAULT NULL,
  value decimal(10, 0) DEFAULT NULL,
  alive tinyint(1) DEFAULT NULL COMMENT 'alive or dead. alive = 1 true'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'chess figures';

--
-- Create table `colors`
--
CREATE TABLE colors (
  id int(11) DEFAULT NULL,
  name varchar(50) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `chess_players`
--
CREATE TABLE chess_players (
  id int(11) DEFAULT NULL,
  name varchar(50) DEFAULT NULL,
  color_id varchar(255) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `chess_notation_db`
--
CREATE TABLE chess_notation_db (
  id int(11) DEFAULT NULL,
  move_number int(11) DEFAULT NULL COMMENT '0-0 0-0-0 etc',
  id_figure int(11) DEFAULT NULL,
  old_pos_chessboard_id int(11) DEFAULT NULL COMMENT 'chessboard_id',
  new_pos_chessboard_id int(11) DEFAULT NULL COMMENT 'chessboard_id'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `chess notation_ht`
--
CREATE TABLE `chess notation_ht` (
  id int(11) DEFAULT NULL,
  white_move char(20) DEFAULT NULL,
  black_move char(20) DEFAULT NULL
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'human text';

-- 
-- Dumping data for table move_options
--
-- Table chess_db.move_options does not contain any data (it is empty)

-- 
-- Dumping data for table main_chessboard
--
-- Table chess_db.main_chessboard does not contain any data (it is empty)

-- 
-- Dumping data for table figures
--
-- Table chess_db.figures does not contain any data (it is empty)

-- 
-- Dumping data for table colors
--
-- Table chess_db.colors does not contain any data (it is empty)

-- 
-- Dumping data for table chess_players
--
-- Table chess_db.chess_players does not contain any data (it is empty)

-- 
-- Dumping data for table chess_notation_db
--
-- Table chess_db.chess_notation_db does not contain any data (it is empty)

-- 
-- Dumping data for table `chess notation_ht`
--
-- Table chess_db.`chess notation_ht` does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;